In [1]:
import numpy as np
scores = np.array([[2, 1, 5],
                   [7, 3, 2],
                   [4, 9, 8],
                   [1, 5, 4]])
scores

array([[2, 1, 5],
       [7, 3, 2],
       [4, 9, 8],
       [1, 5, 4]])

In [2]:
m = scores.shape[0]
max_scores = np.reshape(np.max(scores, axis=1), (m,1))
max_scores

array([[5],
       [7],
       [9],
       [5]])

In [3]:
scores - max_scores

array([[-3, -4,  0],
       [ 0, -4, -5],
       [-5,  0, -1],
       [-4,  0, -1]])

In [4]:
exp_scores = np.exp(scores - max_scores)
exp_scores

array([[0.04978707, 0.01831564, 1.        ],
       [1.        , 0.01831564, 0.00673795],
       [0.00673795, 1.        , 0.36787944],
       [0.01831564, 1.        , 0.36787944]])

In [5]:
probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
probs

array([[0.04661262, 0.01714783, 0.93623955],
       [0.97555875, 0.01786798, 0.00657326],
       [0.00490169, 0.72747516, 0.26762315],
       [0.01321289, 0.72139918, 0.26538793]])

In [6]:
y = np.array([1, 0, 2, 0])
y

array([1, 0, 2, 0])

In [7]:
loss = np.sum(-np.log(probs[range(m), y]))
loss

9.735366864411176

In [8]:
loss /= m
loss

2.433841716102794

In [9]:
# loss += regularization 